---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dassimEcoli

<!-- badges: start -->
<!-- badges: end -->

The dassimEcoli R package contains data and code to replicate the analysis of the manuscript:
  
<br />

*Genomic and diversity of carried _E coli_ isolates  in Blantyre, Malawi *

<br />

Joseph M Lewis^1,2,3,4^, , Madalitso Mphasa^1^, Rachel Banda^1^,  Matthew Beale^4^, Jane Mallewa^5^, Eva Heinz^2^, Nicholas R Thomson^4^, Nicholas A Feasey^1,2^

1. Malawi Liverpool Wellcome Clinical Research Programme, Blantyre, Malawi
2. Department of Clinical Sciences, Liverpool School of Tropical Medicine, Liverpool, UK
3. Department of Clinical Infection, Microbiology and Immunology, University of Liverpool, Liverpool, UK
4. Wellcome Sanger Institute, Hinxton, UK
5. College of Medicine, University of Malawi, Malawi

## Installing and accessing data

Install the package from GitHub:

``` r
install.packages("devtools")
devtools::install_github("https://github.com/joelewis101/dassimEcoli")
```

Or check out the source code at [GitHub](https://github.com/joelewis101/dassimEcoli)

This analysis is available as a package vignette; this can be built when downloading the package by typing:

``` r
devtools::install_github("https://github.com/joelewis101/dassimEcoli", build_vignettes = TRUE )
```

Alternatively the source code for the vignette is `analysis.Rmd` in the `vignettes/` folder of this repo or the  [pkgdown](https://joelewis101.github.io/dassimKlebs/) site for this package has a rendered version, as well as variable definitions for the datasets.

